package Day2;

public class BlackTea implements Tea{

    @Override
    public void steps()
    {
        System.out.println("1. take some water \n 2. take some milk \n 3.");

    }

    @Override
    public void benefits()
    {
        /// todo autogenerated method stub
        System.out.println(" tea refresh mood");

    }
}
