package Day2;

public class Coffee implements Tea{

    @Override
    public void steps()
    {
        System.out.println("1. take some water \n 2. take some milk \n 3. take some suger \n take some coffee powder \n ");

    }

    @Override
    public void benefits()
    {
        /// todo autogenerated method stub
        System.out.println(" coffee refresh mood");

    }

}
